import{a as v,S,i as s}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const q="https://pixabay.com/api/",B="53454682-c39aa10f124dd5ded9ba537e3";async function m(o,r=1){const t={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await v.get(q,{params:t})).data}const u=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function M({largeImageURL:o,webformatURL:r,tags:t,likes:a,views:e,comments:n,downloads:i}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${o}">
        <img class="gallery-image" src="${r}" alt="${t}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${e}</p>
        <p><b>Comments:</b> ${n}</p>
        <p><b>Downloads:</b> ${i}</p>
      </div>
    </li>
  `}function $(o){return o.map(M).join("")}function H(){u.innerHTML=""}function h(o,{append:r=!1}={}){const t=$(o);r?u.insertAdjacentHTML("beforeend",t):u.innerHTML=t,E.refresh()}function p(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function b(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}const d={form:document.querySelector(".form"),input:document.querySelector("input"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")};let l=1,w="",f=0;c();d.form.addEventListener("submit",async o=>{o.preventDefault();const r=d.input.value.trim();if(!r){s.warning({message:"Please enter a search query!"});return}w=r,l=1,H(),c(),p();try{const t=await m(r,l);if(f=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query."});return}h(t.hits),f<=15?(c(),s.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{s.error({message:"Something went wrong. Try again later."})}finally{L()}});d.loadMoreBtn.addEventListener("click",async()=>{l+=1,c(),p();try{const o=await m(w,l);h(o.hits,{append:!0});const r=d.gallery.firstElementChild,{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*15>=f?(c(),s.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{s.error({message:"Error while loading more images."})}finally{L()}});
//# sourceMappingURL=index.js.map
